services:

  kong-database:
    image: postgres:17
    container_name: kong-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
      interval: 5s
      timeout: 5s
      retries: 10

  kong-migrations:
    image: kong:3.9
    container_name: kong-migrations
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap

  kong:
    image: kong:3.9
    container_name: kong
    restart: unless-stopped
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong

      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  users:
    build:
      context: ./service/user-service
    container_name: novamarket-users
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:asad123@users-db:5432/users
    ports:
      - "9001:9001"
    depends_on:
      - users-db

  users-db:
    image: postgres:17
    container_name: novamarket-users-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asad123
      POSTGRES_DB: users
    volumes:
      - users-db-data:/var/lib/postgresql/data
  products:
    build:
      context: ./service/product-service
    container_name: novamarket-products
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:asad123@products-db:5432/products
    ports:
      - "9002:9002"
    depends_on:
      - products-db

  products-db:
    image: postgres:17
    container_name: novamarket-products-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asad123
      POSTGRES_DB: products
    volumes:
      - products-db-data:/var/lib/postgresql/data
  orders:
    build:
      context: ./service/order-service
    container_name: novamarket-orders
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:asad123@orders-db:5432/orders
    ports:
      - "9003:9003"
    depends_on:
      - orders-db

  orders-db:
    image: postgres:17
    container_name: novamarket-orders-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asad123
      POSTGRES_DB: orders
    volumes:
      - orders-db-data:/var/lib/postgresql/data

volumes:
  kong-db-data:
  users-db-data:
  products-db-data:
  orders-db-data: